import { ConflictQuizQuestion } from "@/lib/conflictQuiz/types";

export const conflictQuizQuestions: ConflictQuizQuestion[] = [
  // Section A: Communication Style Identification
  {
    id: "A1",
    section: "A",
    question: "When my partner brings up a concern about something I did, my first reaction is usually to:",
    options: [
      { id: "a", text: "Explain my perspective right away", scores: { expresser: 3, analyzer: 3 } },
      { id: "b", text: "Apologize to smooth things over quickly", scores: { harmonizer: 3, pursuer: 3 } },
      { id: "c", text: "Feel criticized and need some space", scores: { withdrawer: 3, harmonizer: 3 } },
      { id: "d", text: "Ask questions to understand their experience better", scores: { secure: 3, analyzer: 3 } },
      { id: "e", text: "Point out something they did that bothered me too", scores: { expresser: 3, pursuer: 3 } },
    ],
  },
  {
    id: "A2",
    section: "A",
    question: "During a disagreement, I tend to:",
    options: [
      { id: "a", text: "Want to talk it through right away until we resolve it", scores: { pursuer: 3, expresser: 3 } },
      { id: "b", text: "Need time alone to process before I can discuss calmly", scores: { withdrawer: 3, analyzer: 3 } },
      { id: "c", text: "Become more animated or raise my voice", scores: { expresser: 3, pursuer: 3 } },
      { id: "d", text: "Get quiet and shut down emotionally", scores: { withdrawer: 3, harmonizer: 3 } },
      { id: "e", text: "Look for compromise quickly to reduce tension", scores: { harmonizer: 3, secure: 3 } },
    ],
  },
  {
    id: "A3",
    section: "A",
    question: "When I'm upset with my partner, I usually:",
    options: [
      { id: "a", text: "Tell them directly as soon as I realize it", scores: { expresser: 3, secure: 3 } },
      { id: "b", text: "Wait until I've completely calmed down before bringing it up", scores: { analyzer: 3, withdrawer: 3 } },
      { id: "c", text: "Drop hints and hope they notice something's wrong", scores: { harmonizer: 3, withdrawer: 3 } },
      { id: "d", text: "Hold it in until it builds up and comes out over something small", scores: { withdrawer: 3, expresser: 3 } },
      { id: "e", text: "Write down or mentally organize my thoughts before speaking", scores: { analyzer: 3, secure: 3 } },
    ],
  },
  {
    id: "A4",
    section: "A",
    question: "When my partner says \"We need to talk,\" my immediate feeling is:",
    options: [
      { id: "a", text: "Anxious or worried about what's coming", scores: { pursuer: 3, harmonizer: 3 } },
      { id: "b", text: "Defensive, like I'm about to be blamed for something", scores: { withdrawer: 3, expresser: 3 } },
      { id: "c", text: "Ready and willing to address whatever it is", scores: { secure: 3, pursuer: 3 } },
      { id: "d", text: "Annoyed at being put on the spot", scores: { withdrawer: 3, analyzer: 3 } },
      { id: "e", text: "Curious and open about what's on their mind", scores: { secure: 3, analyzer: 3 } },
    ],
  },
  {
    id: "A5",
    section: "A",
    question: "During conflict, my body physically:",
    options: [
      { id: "a", text: "Gets tense, heart races, I want to escape the situation", scores: { withdrawer: 3, harmonizer: 3 } },
      { id: "b", text: "Gets energized and ready to engage", scores: { expresser: 3, pursuer: 3 } },
      { id: "c", text: "Shuts down, goes numb, or disconnects", scores: { withdrawer: 3, harmonizer: 3 } },
      { id: "d", text: "Stays relatively calm and stable", scores: { secure: 3, analyzer: 3 } },
      { id: "e", text: "Varies significantly depending on the topic", scores: { pursuer: 2, withdrawer: 2, analyzer: 2, harmonizer: 2, expresser: 2, secure: 2 } },
    ],
  },
  {
    id: "A6",
    section: "A",
    question: "After an argument ends, I typically:",
    options: [
      { id: "a", text: "Want to fully discuss what happened and resolve any lingering issues", scores: { pursuer: 3, secure: 3 } },
      { id: "b", text: "Need significant space and time before reconnecting", scores: { withdrawer: 3, analyzer: 3 } },
      { id: "c", text: "Act like it didn't happen and move on quickly", scores: { harmonizer: 3, withdrawer: 3 } },
      { id: "d", text: "Replay the conversation in my head for hours or even days", scores: { analyzer: 3, pursuer: 3 } },
      { id: "e", text: "Try to reconnect physically or affectionately first", scores: { harmonizer: 3, pursuer: 3 } },
    ],
  },
  {
    id: "A7",
    section: "A",
    question: "When I need to give my partner critical feedback, I:",
    options: [
      { id: "a", text: "Say it directly and straightforwardly", scores: { expresser: 3, secure: 3 } },
      { id: "b", text: "Sandwich it between compliments to soften the blow", scores: { harmonizer: 3, analyzer: 3 } },
      { id: "c", text: "Avoid it unless absolutely necessary", scores: { harmonizer: 3, withdrawer: 3 } },
      { id: "d", text: "Feel frustrated because I've mentioned it before without change", scores: { expresser: 3, pursuer: 3 } },
      { id: "e", text: "Ask questions to lead them to realize it themselves", scores: { analyzer: 3, secure: 3 } },
    ],
  },
  {
    id: "A8",
    section: "A",
    question: "I feel most heard by my partner when they:",
    options: [
      { id: "a", text: "Maintain eye contact and give physical cues they're listening", scores: { pursuer: 3, expresser: 3 } },
      { id: "b", text: "Reflect back what I said to confirm understanding", scores: { analyzer: 3, secure: 3 } },
      { id: "c", text: "Ask follow-up questions to go deeper", scores: { analyzer: 3, secure: 3 } },
      { id: "d", text: "Take concrete action based on what I've shared", scores: { expresser: 3, pursuer: 3 } },
      { id: "e", text: "Simply listen without trying to fix or solve anything", scores: { secure: 3, withdrawer: 3 } },
    ],
  },
  {
    id: "A9",
    section: "A",
    question: "During difficult conversations, I'm most likely to use:",
    options: [
      { id: "a", text: "\"You\" statements (\"You always...\", \"You never...\")", scores: { expresser: 3, pursuer: 3 } },
      { id: "b", text: "\"I\" statements (\"I feel...\", \"I need...\")", scores: { secure: 3, analyzer: 3 } },
      { id: "c", text: "Generalizations (\"Everyone thinks...\", \"No one would...\")", scores: { expresser: 3, harmonizer: 3 } },
      { id: "d", text: "Questions to better understand their perspective", scores: { analyzer: 3, secure: 3 } },
      { id: "e", text: "A mix depending on how heated things get", scores: { pursuer: 2, withdrawer: 2, analyzer: 2, harmonizer: 2, expresser: 2, secure: 2 } },
    ],
  },
  {
    id: "A10",
    section: "A",
    question: "When I don't know how to respond in the moment, I:",
    options: [
      { id: "a", text: "Say something anyway to fill the uncomfortable silence", scores: { expresser: 3, pursuer: 3 } },
      { id: "b", text: "Go quiet while I think through my response", scores: { analyzer: 3, withdrawer: 3 } },
      { id: "c", text: "Change the subject to something easier", scores: { harmonizer: 3, withdrawer: 3 } },
      { id: "d", text: "Directly ask for time to gather my thoughts", scores: { secure: 3, analyzer: 3 } },
      { id: "e", text: "Admit out loud that I'm not sure what to say", scores: { secure: 3, expresser: 3 } },
    ],
  },
  // Section B: Response Patterns
  {
    id: "B1",
    section: "B",
    question: "When my partner interrupts me while I'm speaking, I typically:",
    options: [
      { id: "a", text: "Feel frustrated but keep trying to make my point", scores: { expresser: 2, pursuer: 2 } },
      { id: "b", text: "Stop talking and shut down", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "c", text: "Get louder or more insistent to be heard", scores: { expresser: 2, pursuer: 2 } },
      { id: "d", text: "Point out the interruption directly and ask them to let me finish", scores: { secure: 2, expresser: 2 } },
      { id: "e", text: "It doesn't bother me much", scores: { harmonizer: 2, secure: 2 } },
    ],
  },
  {
    id: "B2",
    section: "B",
    question: "When my partner raises their voice during a disagreement, I:",
    options: [
      { id: "a", text: "Match their intensity and energy level", scores: { expresser: 2, pursuer: 2 } },
      { id: "b", text: "Get quiet and withdraw emotionally", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "c", text: "Feel anxious and want to escape the situation", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "d", text: "Ask them to lower their voice before continuing", scores: { secure: 2, analyzer: 2 } },
      { id: "e", text: "Stay relatively calm and unaffected", scores: { secure: 2, analyzer: 2 } },
    ],
  },
  {
    id: "B3",
    section: "B",
    question: "When my partner goes silent during conflict, I:",
    options: [
      { id: "a", text: "Give them space naturally without pushing", scores: { secure: 2, withdrawer: 2 } },
      { id: "b", text: "Feel panicked and try to re-engage them", scores: { pursuer: 2, expresser: 2 } },
      { id: "c", text: "Get more frustrated and insistent that we talk", scores: { pursuer: 2, expresser: 2 } },
      { id: "d", text: "Also go silent and wait them out", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "e", text: "Ask what they need in that moment", scores: { secure: 2, analyzer: 2 } },
    ],
  },
  {
    id: "B4",
    section: "B",
    question: "When I feel dismissed or not heard, I typically:",
    options: [
      { id: "a", text: "Try harder to explain my point in different ways", scores: { pursuer: 2, expresser: 2 } },
      { id: "b", text: "Give up and withdraw from the conversation", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "c", text: "Get emotional (cry, raise my voice, etc.)", scores: { expresser: 2, pursuer: 2 } },
      { id: "d", text: "Shut down emotionally and go cold", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "e", text: "Calmly restate my perspective one more time", scores: { secure: 2, analyzer: 2 } },
    ],
  },
  {
    id: "B5",
    section: "B",
    question: "When my partner criticizes me, my first reaction is to:",
    options: [
      { id: "a", text: "Defend myself and explain why I did what I did", scores: { expresser: 2, pursuer: 2 } },
      { id: "b", text: "Feel hurt and pull away emotionally", scores: { withdrawer: 2, harmonizer: 2 } },
      { id: "c", text: "Counter with their flaws or mistakes", scores: { expresser: 2, pursuer: 2 } },
      { id: "d", text: "Listen and genuinely consider if it's valid", scores: { secure: 2, analyzer: 2 } },
      { id: "e", text: "Apologize quickly to end the tension", scores: { harmonizer: 2, withdrawer: 2 } },
    ],
  },
  // Section C: Communication Goals
  {
    id: "C1",
    section: "C",
    question: "What I most want from improving our communication is:",
    maxSelections: 3,
    options: [
      { id: "a", text: "Less frequent fighting and arguing", scores: {} },
      { id: "b", text: "Feeling genuinely heard and understood", scores: {} },
      { id: "c", text: "Being able to discuss difficult topics without tension", scores: {} },
      { id: "d", text: "My partner understanding my needs without me having to explain repeatedly", scores: {} },
      { id: "e", text: "More emotional intimacy through deeper conversation", scores: {} },
      { id: "f", text: "Resolving conflicts faster when they do happen", scores: {} },
      { id: "g", text: "Breaking the pattern of having the same arguments repeatedly", scores: {} },
      { id: "h", text: "Feeling emotionally safe enough to be vulnerable", scores: {} },
      { id: "i", text: "Better daily check-ins and connection", scores: {} },
    ],
  },
];
